debug: false
management.endpoints.web.exposure.include: "*"
logging:
  level:
    com.board.boardsite: debug
    org.springframework.web.servlet: debug                      #Request / Response bebug 활성화
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: ${POSTGRE_SQL_URL}
    username: postgres
    password: ${POSTGRE_SQL_PWD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_MAIL_ID}
    password: ${GOOGLE_MAIL_PW}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            auth: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    defer-datasource-initialization: true         # 2.5 이상 data.sql 실행
    hibernate.ddl-auto: update                    # table 생성
    open-in-view: false
    show-sql: true                                # 쿼리 보여줌
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100 # N+1 이슈
  h2.console.enabled: false
  sql.init.mode: NEVER
  data.rest:
    base-path: /hal-api
    detection-strategy: annotated
  thymeleaf3.decoupled-logic: true
server:
  port: 8081
servlet:
  multipart:
    maxFileSize: 800MB
    maxRequestSize: 800MB
    enabled: true
    location: C:\Git_project\board-site\src\main\resources\templates\image
custom:
  path:
    upload-images: C:\Git_project\board-site\src\main\resources\templates\image
    thumbnail-images: C:\Git_project\board-site\src\main\resources\templates\thumbnail

import:
  rest-api: ${IMPORT_KEY}
  rest-api-secret: ${IMPORT_SECRET}
naver:
  client-id: ${NAVER_ID}
  client-secret: ${NAVER_PW}
  callback-url: https://board-site-production.up.railway.app/NaverLoginCallback
kakao:
  rest-api-key: ${KAKAO_ID}
  callback-url: https://board-site-production.up.railway.app/NaverLoginCallback
  admin-key: ${KAKAO_PW}
jwt:
  secret-key: board_site.trip_web_application.secret_key
  #30 days
  token.expired-time-ms: 2592000000
batch:
  initialize-schema: never

cloudinary:
  cloud_name: ${CLOUDINARY_ID}
  api_key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_PW}

---
