debug: false
management.endpoints.web.exposure.include: "*"
logging:
  level:
    com.board.boardsite: debug
    org.springframework.web.servlet: debug                      #Request / Response bebug 활성화
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boardsite
    username: postgres
    password: dkahffk11
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: cohouseol@gmail.com
    password: skdxecuyxmkiabcb
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            auth: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000

  jpa:
    defer-datasource-initialization: true         # 2.5 이상 data.sql 실행
    hibernate.ddl-auto: update                    # table 생성
    open-in-view: false
    show-sql: true                                # 쿼리 보여줌
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100 # N+1 이슈
  h2.console.enabled: false
  sql.init.mode: NEVER
  data.rest:
    base-path: /hal-api
    detection-strategy: annotated
  thymeleaf3.decoupled-logic: true
server:
  port: 8081
servlet:
  multipart:
    maxFileSize: 800MB
    maxRequestSize: 800MB
    enabled: true
    location: C:\Git_project\board-site\src\main\resources\templates\image
custom:
  path:
    upload-images: C:\Git_project\board-site\src\main\resources\templates\image
    thumbnail-images: C:\Git_project\board-site\src\main\resources\templates\thumbnail

import:
  rest-api: 3071870338636273
  rest-api-secret: 0nejijihcCxf0Fi7io0zia5NNtaw0tv7z15FUDhLJi8w0h85ieWdC2zgRyqK9KAS0T2yA0PHeABpwYOd
naver:
  client-id: VI3PelSRuX5_E4NdPZHj
  client-secret: CHD4HaNzd4
  callback-url: http://localhost:8081/NaverLoginCallback
kakao:
  rest-api-key: fa8b9147c368820f00315b9e2b68eae5
  callback-url: http://localhost:8081/KakaoLoginCallback
  admin-key: cce05f289cb3058bb7a61d4d1fce24b2
jwt:
  secret-key: board_site.trip_web_application.secret_key
  #30 days
  token.expired-time-ms: 2592000000
batch:
  initialize-schema: never

cloudinary:
  cloud_name: hhnetuz2l
  api_key: 165883987375785
  api_secret: TM8jN2lzQtwyQpLkyZpYwsG0EjM

---
spring:
  config.activate.on-profile: heroku
  datasource:
    url: jdbc:postgresql://ec2-3-213-66-35.compute-1.amazonaws.com:5432/d2uku28in0vnr7
    username: txwxckyioaetcl
    password: c4cf86f02a9886d487b8c59bda5051dea8ae4370d1f3177318241ca211ba975f
    platform: postgres
    driver-class-name: org.postgresql.Driver
  jpa.hibernate.ddl-auto: update
#  sql.init.mode: never

servlet:
  multipart:
    maxFileSize: 800MB
    maxRequestSize: 800MB
    enabled: true
    location: C:\Git_project\board-site\src\main\resources\templates\image
custom:
  path:
    upload-images: C:\Git_project\board-site\src\main\resources\templates\image
    thumbnail-images: C:\Git_project\board-site\src\main\resources\templates\thumbnail